#!/usr/bin/env bash

printf 'backend_started\n' >>"$CADDY_TEST_EVENTS"
trap 'printf "backend_term\n" >>"$CADDY_TEST_EVENTS"; exit 0' TERM INT

case "${CADDY_TEST_BACKEND_MODE:-wait}" in
  delayed_ready)
    sleep 0.3
    printf 'backend_checked_before_ready\n' >>"$CADDY_TEST_EVENTS"
    if grep -q '^caddy_started$' "$CADDY_TEST_EVENTS"; then
      printf 'caddy_started_before_ready\n' >>"$CADDY_TEST_EVENTS"
    fi
    touch "$CADDY_TEST_READY_FILE"
    ;;
  exit_before_ready)
    sleep 0.3
    exit 23
    ;;
  exit_after_ready)
    sleep 0.3
    exit 23
    ;;
esac

while true; do
  sleep 0.1
done
